<a href="https://colab.research.google.com/github/afpalmasan/Fundamentos-NumPy-Pandas/blob/maester/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY ARRAY**

---



In [1]:
import numpy as np

In [ ]:
lista =[1,2,3,4,5,6,7,8,9]
array = np.array(lista)
type(array)

numpy.ndarray

In [ ]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array[0] + array [5]

7

In [ ]:
matriz
matriz[0,2]

3

In [ ]:
array[::3]

array([1, 4, 7])

In [ ]:
array[1:6:2]

array([2, 4, 6])

**TIPOS DE DATOS NUMPY**

---



In [ ]:
arr = np.array([1,2,3,4])
arr.dtype


dtype('int64')

In [ ]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [ ]:
arr.astype(np.float64)

array([1., 2., 3., 4.])

In [ ]:
arr = np.array([1,2,3,4])
arr= arr.astype(np.bool_)
arr

array([ True,  True,  True,  True])

In [ ]:
arr = np.array([1,2,3,4])
arr= arr.astype(np.string_)
arr

array([b'1', b'2', b'3', b'4'], dtype='|S21')

In [ ]:
arr = np.array(['1','2','3','4'])
arr= arr.astype(np.int8)
arr

array([1, 2, 3, 4], dtype=int8)

**DIMENSIONES EN NUMPY**

---



In [ ]:
scalar = np.array(21)
print(scalar)
scalar.ndim

21


0

In [ ]:
vector = np.array([4,2,3])
print(vector)
vector.ndim

[4 2 3]


1

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
tensor = np.array([[[1,2,3,6],[1,2,3,4]],[[4,5,6,7],[4,5,6,5]]])
print(tensor)
tensor.ndim

[[[1 2 3 6]
  [1 2 3 4]]

 [[4 5 6 7]
  [4 5 6 5]]]


3

## Agregar o eliminar dimensiones

In [ ]:
vector = np.array([4,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[4 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[4 2 3]]]]]]]]]] 10
[4 2 3] 1


## Creando Arrays en NumPy

---



In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(3)
np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(4,4)

array([[0.04394827, 0.28251545, 0.68907376, 0.54510546],
       [0.44701855, 0.97581096, 0.7430102 , 0.33787875],
       [0.78405182, 0.71881249, 0.70652128, 0.05314065],
       [0.63212471, 0.147209  , 0.38614253, 0.70869202]])

In [ ]:
np.random.randint(1,15)

10

In [ ]:
np.random.randint(1,100,(10,10)) #(dato inicial, dato final, (tupla para definir matriz))

array([[92,  4, 44, 88, 69, 11, 32, 53, 81, 65],
       [ 6, 64, 84, 19,  6, 17,  9, 47, 87, 17],
       [68, 89, 22, 53, 98, 21,  1, 50, 80, 42],
       [47, 68, 36, 83, 85, 88, 82, 27, 45, 25],
       [85, 56, 67, 97, 78, 27, 56, 93, 63, 11],
       [34, 90, 15, 79,  2, 56, 59, 59, 35, 96],
       [80, 71, 17, 95, 67, 10, 75, 76, 91, 75],
       [26, 97, 18, 46, 19, 48, 36, 69, 16, 92],
       [21, 62, 64, 84, 18, 84, 59, 28, 85, 10],
       [16,  7, 23, 52, 98, 53, 32, 29, 36, 30]])

## Shape y Reshape

---



In [ ]:
arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [ ]:
arr

array([[4, 1],
       [2, 7],
       [1, 4]])

In [ ]:
arr.reshape(1,6)

array([[4, 1, 2, 7, 1, 4]])

In [ ]:
arr.reshape(2,3)

array([[4, 1, 2],
       [7, 1, 4]])

In [ ]:
np.reshape(arr,(2,3), 'A')

array([[4, 1, 2],
       [7, 1, 4]])

## Funciones Principales NumPy

---



In [3]:
arr = np.random.randint(1,20,10)
matriz = arr.reshape(2,5)
matriz

array([[16,  1,  9,  6, 15],
       [12, 12,  1, 12, 13]])

In [4]:
arr.max()

16

In [9]:
matriz.max(1) ## se puede espeficicar el eje para definir el maximo

array([16, 13])

In [10]:
arr.argmax()

0

In [12]:
matriz.argmax(0) # devuelve el indice con el valor mas alto

array([0, 1, 0, 1, 0])

In [13]:
arr.min()

1

In [14]:
matriz.min(0)


array([12,  1,  1,  6, 13])

In [15]:
matriz.argmin(0) # devuelve el indice con el valor minimo


array([1, 0, 1, 0, 1])

In [17]:
arr

array([16,  1,  9,  6, 15, 12, 12,  1, 12, 13])

In [18]:
arr.ptp() # devuelve la diferencia entre el valor mas alto y el mas bajo del arreglo

15

In [19]:
matriz.ptp(0) # devuelve la diferencia entre el valor mas alto y el mas bajo de la matriz segun el eje que se indique

array([ 4, 11,  8,  6,  2])

In [20]:
np.percentile(arr,50) #devuelve el percentil de un arrglo

12.0

In [23]:
arr.sort() ## Ordena el arreglo
arr

array([ 1,  1,  6,  9, 12, 12, 12, 13, 15, 16])

In [24]:
np.median(arr)

12.0

In [25]:
np.median(matriz,0)

array([ 6.5,  6.5,  9.5, 12. , 14. ])

In [26]:
np.std(arr) # desviacin estandar

5.1

In [27]:
np.var(arr)

26.009999999999998

In [28]:
np.mean(arr) ## calcular la mediana o average del arreglo

9.7

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6], ndmin=2)

In [43]:
a.ndim

2

In [48]:

b.ndim

2

In [49]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
np.concatenate((a,b.T),axis=1) # se aplica la transpuesta para concatenar el arreglo de forma columnar

array([[1, 2, 5],
       [3, 4, 6]])

In [4]:
b.T

array([[5],
       [6]])

## FUNCION COPY

---



In [29]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
trozo_arr = arr[0:6]
trozo_arr

array([1, 2, 3, 4, 5, 6])

In [31]:
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

In [32]:
arr

array([ 0,  0,  0,  0,  0,  0,  7,  8,  9, 10])

In [33]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  7,  8,  9, 10])

In [34]:
arr_copy[:] = 10
arr_copy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [35]:
arr

array([ 0,  0,  0,  0,  0,  0,  7,  8,  9, 10])

## CONDICIONES

In [37]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [39]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [40]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [41]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [43]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [45]:
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)

## OPERACIONES

---



In [46]:
lista = [1,2]
lista

[1, 2]

In [47]:
lista * 2

[1, 2, 1, 2]

In [54]:
arr1 = np.arange(0,10)
arr2 = arr1.copy()
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
arr1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
1/ arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.01010101, 0.01010101, 0.01010101, 0.01010101, 0.01010101])

In [57]:
arr ** 2

array([ 1,  4,  9, 16, 25, 73, 73, 73, 73, 73], dtype=int8)

In [58]:
arr1 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
arr1 * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
matriz = arr1.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [66]:
np.matmul(matriz,matriz2.T) # Operacion de Producto punto

array([[ 30,  80],
       [ 80, 255]])

In [67]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])